import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./ui/sidebar/page";
import Navbar from "./ui/navbar/page";
import Footer from "./ui/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <div className="flex-auto bg-zinc-950 w-[24%]">
            <Sidebar />
          </div>
          <div className="flex-auto  bg-zinc-950 w-4/5">
            <Navbar />
            {children}
          </div>
        </main>
        <footer className="relative">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
